# Generated by Django 3.2.4 on 2022-06-14 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermodel',
            table='user',
        ),
    ]
