# Generated by Django 3.2.4 on 2022-06-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(help_text='年龄不能小于0', verbose_name='年龄'),
        ),
    ]
